branch-defaults:
  master:
    environment: ticketee-iLED
    group_suffix: null
global:
  application_name: ticketee-iLED
  branch: null
  default_ec2_keyname: null
  default_platform: Ruby 2.3 (Puma)
  default_region: ap-northeast-2
  profile: eb-cli
  repository: null
  sc: git
